# C flags
cflags-y	+= -Os

# HotPlugs #
#obj-$(CONFIG_ASMP)           	        += autosmp.o
obj-$(CONFIG_BLU_PLUG)                  += blu_plug.o
#obj-$(CONFIG_INTELLI_PLUG)              += intelli_plug.o
#obj-$(CONFIG_MSM_HOTPLUG)		+= msm_hotplug.o
#obj-$(CONFIG_THUNDER_PLUG)              += thunder_plug.o
